apiVersion: v1
kind: Pod
metadata:
  name: auth-pod
  labels:
    app: auth-pod
spec:
  containers:
    - name: auth
      image: jboss/keycloak
      env:
        - name: KEYCLOAK_USER
          value: "admin"
        - name: KEYCLOAK_PASSWORD
          value: "secret"

---

apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: auth-service
spec:
  selector:
    # Loadbalance traffic across Pods matching this label selector
    app: auth-pod
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 8080
      nodePort : 30080
  type: NodePort