apiVersion: v1
kind: Pod
metadata:
  name: database-pod
  labels:
    app: database-pod
spec:
  containers:
    - name: database
      image: postgres:12
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "secret"
        - name: POSTGRES_DB
          value: "postgres"

---
apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: database-service
spec:
  selector:
    app: database-pod
  ports:
    - name: tcp
      port: 5432
      targetPort : 5432
  type : ClusterIP