version: '3.1'
services:
  postcode-db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postcode
      POSTGRES_PASSWORD: postcode
      POSTGRES_DB: postcode

