version: '3.1'
services:
  postcode-db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres

  auth-server:
    image: jboss/keycloak
    volumes:
      - ./tmp:/tmp
    ports:
      - "8070:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: secret
      KEYCLOAK_IMPORT: /tmp/test-realm.json