DELETE from POSTCODE;
INSERT INTO POSTCODE(CODE,SUBURB,STATE) values (3192, 'Cheltenham', 'VIC');
INSERT INTO POSTCODE(CODE,SUBURB,STATE) values (2795, 'CHARLTON', 'NSW');
INSERT INTO POSTCODE(CODE,SUBURB,STATE) values (3525, 'CHARLTON', 'VIC');
INSERT INTO POSTCODE(CODE,SUBURB,STATE) values (0822, 'CHARLOTTE', 'NT');